/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.95
 * Generated at: 2023-11-23 13:30:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<STYLE type=\"text/css\">\r\n");
      out.write("    #login {\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        height: 280px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        top: 20%;\r\n");
      out.write("        margin-left: -200px;\r\n");
      out.write("        margin-top: -140px;\r\n");
      out.write("        border: 1px;\r\n");
      out.write("       /* background-color: #befff1;*/\r\n");
      out.write("        align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #form {\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        height: 160px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        margin-left: -150px;\r\n");
      out.write("        margin-top: -80px;\r\n");
      out.write("    }\r\n");
      out.write("</STYLE>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>《戒灵》添加服务器</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"login\">\r\n");
      out.write("    <h1 style=\"color: #000000\" onresize=\"50\">《戒灵》添加服务器</h1>\r\n");
      out.write("    <div id=\"form\">\r\n");
      out.write("        <form action=\"regist\" method=\"post\" accept-charset=\"UTF-8\">\r\n");
      out.write("            <p>name: <input type=\"text\" name=\"name\" placeholder=\"请输入游戏服务器名字\" required /></p>\r\n");
      out.write("            <p>ip: <input type=\"text\" name=\"ip\" pattern=\"(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)\" placeholder=\"请输入服务器IP地址\" required /></p>\r\n");
      out.write("            <p>port: <input type=\"text\" value=\"9000\" name=\"port\" pattern=\"[0-9]{0,6}\" placeholder=\"请输入端口号\" required /></p>\r\n");
      out.write("            <p>server_id: <input type=\"text\" name=\"server_id\" pattern=\"[0-9]{0,6}\" placeholder=\"请输入server id\" required />  </p>\r\n");
      out.write("            <p>channel:<select name=\"channel\">\r\n");
      out.write("                <option value=\"pc\" selected>pc</option>\r\n");
      out.write("                <option value=\"qq\">qq</option>\r\n");
      out.write("                <option value=\"wx\">wx</option>\r\n");
      out.write("            </select></p>\r\n");
      out.write("            <p>sub_channel: <input type=\"text\" name=\"sub_channel\" required /></p>\r\n");
      out.write("            <p>plat:<select name=\"plat\">\r\n");
      out.write("                <option value=\"android\" selected>android</option>\r\n");
      out.write("                <option value=\"ios\">ios</option>\r\n");
      out.write("            </select></p>\r\n");
      out.write("            <p>state: <input type=\"text\" value=\"0\" name=\"state\"  /></p>\r\n");
      out.write("            <p>open_time: <input type=\"text\" value=\"0\" name=\"open_time\" /></p>\r\n");
      out.write("            <p>isnew: <input type=\"text\" value=\"0\" name=\"isnew\" /></p>\r\n");
      out.write("            <input type=\"submit\" value=\"Submit\"/>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
