/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.95
 * Generated at: 2023-10-20 11:34:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.wm.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xnx3.j2ee.Global;
import com.xnx3.j2ee.util.SystemUtil;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/software/tomcat/apache-tomcat-8.5.95/webapps/wangmarket/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1678953640000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
    _jspx_imports_classes.add("com.xnx3.j2ee.util.SystemUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

//标题
String title = request.getParameter("title");
if(title == null ){
	title = SystemUtil.get("SITE_NAME");
}else{
	title=title+"_"+SystemUtil.get("SITE_NAME");
}

//关键字
String keywords = request.getParameter("keywords");
if(keywords == null ){
	keywords = SystemUtil.get("SITE_KEYWORDS");
}

//描述
String description = request.getParameter("description");
if(description == null ){
	description = SystemUtil.get("SITE_DESCRIPTION");
}

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\" style=\"font-size:16px;\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<title>");
      out.print(title );
      out.write("</title>\n");
      out.write("<meta name=\"keywords\" content=\"");
      out.print(keywords );
      out.write("\" />\n");
      out.write("<meta name=\"description\" content=\"");
      out.print(description );
      out.write("\" />\n");
      out.write("\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"author\" content=\"管雷鸣\">\n");
      out.write("<!-- wm/common/head -->\n");
      out.write("<!-- layer 、 layui -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(SystemUtil.get("STATIC_RESOURCE_PATH") );
      out.write("module/layui/css/layui.css?v=");
      out.print(Global.VERSION );
      out.write("\">\n");
      out.write("<script src=\"");
      out.print(SystemUtil.get("STATIC_RESOURCE_PATH") );
      out.write("module/layui/layui.js?v=");
      out.print(Global.VERSION );
      out.write("\"></script>\n");
      out.write("<script src=\"");
      out.print(SystemUtil.get("STATIC_RESOURCE_PATH") );
      out.write("module/msg/msg.js?v=");
      out.print(Global.VERSION );
      out.write("\"></script>\n");
      out.write("<script src=\"");
      out.print(SystemUtil.get("STATIC_RESOURCE_PATH") );
      out.write("module/request/request.js?v=");
      out.print(Global.VERSION );
      out.write("\"></script>\n");
      out.write("<!-- 商城及接口相关，要废弃 -->\n");
      out.write("<!-- <script src=\"//res.zvo.cn/shop/shop.js\"></script>-->\n");
      out.write("<script>\n");
      out.write("//加载 layer 模块\n");
      out.write("layui.use('layer', function(){\n");
      out.write("	layer = layui.layer;\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print(SystemUtil.get("STATIC_RESOURCE_PATH") );
      out.write("module/js/jquery-2.1.4.js\"></script>\n");
      out.write("\n");
      out.write("<!-- order by 列表的排序 -->\n");
      out.write("<script src=\"");
      out.print(SystemUtil.get("STATIC_RESOURCE_PATH") );
      out.write("module/js/iw.js?v=");
      out.print(Global.VERSION );
      out.write("\"></script>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print(SystemUtil.get("STATIC_RESOURCE_PATH") );
      out.write("module/wm/wm.js?v=");
      out.print(Global.VERSION );
      out.write("\"></script>\n");
      out.write("\n");
      out.write("<!-- vue -->\n");
      out.write("<script src=\"");
      out.print(SystemUtil.get("STATIC_RESOURCE_PATH") );
      out.write("module/vue/vue-3.1.4.js\"></script>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("/*列表页头部form搜索框*/\n");
      out.write(".toubu_xnx3_search_form{\n");
      out.write("	padding-top:10px;\n");
      out.write("	padding-bottom: 10px;\n");
      out.write("}\n");
      out.write("/*列表页头部搜索，form里面的搜索按钮*/\n");
      out.write(".iw_list_search_submit{\n");
      out.write("	margin-left:22px;\n");
      out.write("}\n");
      out.write("/* 列表页，数据列表的table */\n");
      out.write(".iw_table{\n");
      out.write("	margin:0px;\n");
      out.write("}\n");
      out.write("/* 详情页，table列表详情展示，这里是描述，名字的td */\n");
      out.write(".iw_table_td_view_name{\n");
      out.write("	width:150px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* edit.jsp 编辑页面，输入框下面的灰色小字的说明 */\n");
      out.write(".layui-form-item .explain{\n");
      out.write("	font-size: 11px;\n");
      out.write("	color: gray;\n");
      out.write("	padding-top: 2px;\n");
      out.write("	text-align: left;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("/**\n");
      out.write(" * 获取网址的get参数。\n");
      out.write(" * @param name get参数名\n");
      out.write(" * @returns value\n");
      out.write(" */\n");
      out.write("function getUrlParams(name){\n");
      out.write("	console.log('getUrlParams 已废弃，请使用 wm.getUrlParams(name)');\n");
      out.write("	return wm.getUrlParams(name);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function formatTime(number,format) {\n");
      out.write("	console.log('formatTime 已废弃，请使用 wm.formatTime(number,format)');\n");
      out.write("	return wm.formatTime(number,format);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function post(api, data, func) {\n");
      out.write("	console.log('post 已废弃，请使用 wm.post(api, data, func); 或者重写本post方法');\n");
      out.write("	return wm.post(api, data, func);\n");
      out.write("}\n");
      out.write("\n");
      out.write("//如果未登录，那么拦截，弹出提示，并跳转到登录页面\n");
      out.write("function checkLogin(data){\n");
      out.write("	if(data.result == '2'){\n");
      out.write("		//未登录\n");
      out.write("		msg.info('请先登录', function(){\n");
      out.write("			window.location.href=\"/wm/login/login.jsp\";\n");
      out.write("		});\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
