/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.95
 * Generated at: 2023-10-20 11:34:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.wm.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.xnx3.wangmarket.Authorization;
import com.xnx3.j2ee.util.SafetyUtil;
import com.xnx3.j2ee.Global;

public final class siteLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/software/tomcat/apache-tomcat-8.5.95/webapps/wangmarket/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/D:/software/tomcat/apache-tomcat-8.5.95/webapps/wangmarket/WEB-INF/lib/wm-3.10.jar!/META-INF/xnx3.tld", Long.valueOf(1693460496000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1678953640000L));
    _jspx_dependants.put("jar:file:/D:/software/tomcat/apache-tomcat-8.5.95/webapps/wangmarket/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/wm-3.10.jar", Long.valueOf(1695010320000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.wangmarket.Authorization");
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.xnx3.j2ee.util.SafetyUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//登陆用户名
	String username = SafetyUtil.filter(request.getParameter("username"));
	if(username == null || (username != null && username.equals("null"))){
		username = "";
	}
	
	//登陆密码
	String password = SafetyUtil.filter(request.getParameter("password"));
	if(password == null || (password != null && password.equals("null"))){
		password = "";
	}
 
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/wm/common/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("登录", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("    <!-- Meta tag Keywords -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${STATIC_RESOURCE_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("plugin/login/css/Noto-Sans_JP.css\" rel=\"stylesheet\">  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${STATIC_RESOURCE_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("plugin/login/css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${STATIC_RESOURCE_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("plugin/login/css/font-awesome.min.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        .content-wthree input{\r\n");
      out.write("            background: #FFFFFF;\r\n");
      out.write("        }\r\n");
      out.write("        .codeBox{\r\n");
      out.write("            background-color: #FFFFFF;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"block\" class=\"w3lvide-content\" data-vide-bg=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${STATIC_RESOURCE_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("plugin/login/images/freelan\" data-vide-options=\"position: 0% 50%\">\r\n");
      out.write("            <!-- /form -->\r\n");
      out.write("            <div class=\"workinghny-form-grid\" style=\"width: 100%\">\r\n");
      out.write("                <div class=\"main-hotair\">\r\n");
      out.write("                    <div class=\"content-wthree\">\r\n");
      out.write("                        <h1><span style=\"\r\n");
      out.write("    font-family: 'Pacifico', cursive;\r\n");
      out.write("    font-size: 50px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    letter-spacing: 5px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("\">");
      out.print(Global.get("SITE_NAME") );
      out.write("</span></h1>\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <input type=\"text\" class=\"text\" name=\"username\" value=\"");
      out.print(username );
      out.write("\" placeholder=\"请输入 用户名/邮箱\" required  lay-verify=\"required\" autocomplete=\"off\">\r\n");
      out.write("                            <input type=\"password\" id=\"password\" class=\"password\" name=\"password\" value=\"");
      out.print(password );
      out.write("\" placeholder=\"请输入密码\"  required  lay-verify=\"required\" autocomplete=\"off\">\r\n");
      out.write("                            <div style=\"position: relative\">\r\n");
      out.write("                                <input type=\"text\" class=\"text\" name=\"code\" placeholder=\"请输入右边验证码\"  required  lay-verify=\"required\" autocomplete=\"off\" style=\"display: block\">\r\n");
      out.write("                                <div class=\"layui-word-aux codeBox\"><img id=\"code\" src=\"captcha.do\" onclick=\"reloadCode();\" style=\"cursor: pointer;\" /></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"layui-form-item\" style=\"display:none\">\r\n");
      out.write("                                <label class=\"layui-form-label\">记住密码</label>\r\n");
      out.write("                                    <div class=\"layui-input-block\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"switch\" lay-skin=\"switch\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <button class=\"btn\" lay-submit lay-filter=\"formDemo\">立即登陆</button>\r\n");
      out.write("\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("           \r\n");
      out.write("     \r\n");
      out.write("        <!-- 未授权用户，请尊重作者劳动成果，保留我方版权标示及链接！否则将追究法律责任。授权参见：http://www.wang.market/price.html -->\r\n");
      out.write("		");
 if(Authorization.copyright){ 
				Date d = new Date();
				SimpleDateFormat df = new SimpleDateFormat("yyyy");
				String nowYear = df.format(d);
		
      out.write("\r\n");
      out.write("			 <!-- copyright-->\r\n");
      out.write("	        ");
      out.write("\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       </div>\r\n");
      out.write("        <!-- //copyright-->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //form section start -->\r\n");
      out.write("      <!-- js -->\r\n");
      out.write("  <script src=\"/plugin/login/js/jquery.min.js\"></script>\r\n");
      out.write("  <!-- //js -->\r\n");
      out.write("  <script>\r\n");
      out.write("  	var STATIC_RESOURCE_PATH = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${STATIC_RESOURCE_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("  	//STATIC_RESOURCE_PATH = '/';\r\n");
      out.write("  </script>\r\n");
      out.write("  <script src=\"/plugin/login/js/jquery.vide.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("//Demo\r\n");
      out.write("layui.use('form', function(){\r\n");
      out.write("	var form = layui.form;\r\n");
      out.write("\r\n");
      out.write("	//监听提交\r\n");
      out.write("	form.on('submit(formDemo)', function(data){\r\n");
      out.write("		msg.loading(\"登陆中\");\r\n");
      out.write("		var d=$(\"form\").serialize();\r\n");
      out.write("		$.post(\"wangmarketLoginSubmit.do\", d, function (result) {\r\n");
      out.write("			msg.close();\r\n");
      out.write("			var obj = JSON.parse(result);\r\n");
      out.write("			try{\r\n");
      out.write("				console.log(obj);\r\n");
      out.write("			}catch(e){}\r\n");
      out.write("			if(obj.result == '1'){\r\n");
      out.write("				localStorage.setItem('token',obj.token);\r\n");
      out.write("				msg.success(\"登陆成功\", function(){\r\n");
      out.write("					window.location.href=obj.info;\r\n");
      out.write("				});\r\n");
      out.write("			}else if(obj.result == '0'){\r\n");
      out.write("				//登陆失败\r\n");
      out.write("				msg.failure(obj.info);\r\n");
      out.write("				reloadCode();\r\n");
      out.write("			}else if(obj.result == '11'){\r\n");
      out.write("				//网站已过期。弹出提示\r\n");
      out.write("				reloadCode();\r\n");
      out.write("				layer.open({\r\n");
      out.write("					title: '到期提示'\r\n");
      out.write("					,content: obj.info\r\n");
      out.write("				});	 \r\n");
      out.write("			}else{\r\n");
      out.write("				reloadCode();\r\n");
      out.write("				msg.failure(result);\r\n");
      out.write("			}\r\n");
      out.write("		}, \"text\");\r\n");
      out.write("		return false;\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//重新加载验证码\r\n");
      out.write("function reloadCode(){\r\n");
      out.write("var code=document.getElementById('code');\r\n");
      out.write("code.setAttribute('src','captcha.do?'+Math.random());\r\n");
      out.write("//这里必须加入随机数不然地址相同我发重新加载\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* \r\n");
      out.write("//检测浏览器，若不是Chrome浏览器，弹出提示\r\n");
      out.write("if(navigator.userAgent.indexOf('Chrome') == -1){\r\n");
      out.write("	layer.open({\r\n");
      out.write("		type: 1\r\n");
      out.write("		,title:'提示'\r\n");
      out.write("		,offset: 'rb' //具体配置参考：offset参数项\r\n");
      out.write("		,content: '<div style=\"padding: 18px; line-height:30px;\">建议使用<a href=\"https://www.baidu.com/s?wd=Chrome\" target=\"_black\" style=\"text-decoration:underline\">Chrome(谷歌)</a>浏览器<br/>其他浏览器登录可能无法正常操作！</div>'\r\n");
      out.write("		,btn: ['下载Chrome','忽略']\r\n");
      out.write("		,btnAlign: 'c' //按钮居中\r\n");
      out.write("		,shade: 0 //不显示遮罩\r\n");
      out.write("		,yes: function(){\r\n");
      out.write("			layer.closeAll();\r\n");
      out.write("			window.open(\"https://www.baidu.com/s?wd=Chrome\");\r\n");
      out.write("		}\r\n");
      out.write("		,btn2: function(){\r\n");
      out.write("			layer.closeAll();\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("} */\r\n");
      out.write("/*\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("	$(\"#block\").vide(\"111video/ocean\"); // Non declarative initialization\r\n");
      out.write("    var instance = $(\"#block\").data(\"vide\"); // Get instance\r\n");
      out.write("   	var video = instance.getVideoObject(); // Get video object\r\n");
      out.write("    instance.destroy(); // Destroy instance\r\n");
      out.write("});\r\n");
      out.write("*/\r\n");
      out.write("</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/wm/common/foot.jsp", out, false);
      out.write(" \r\n");
      out.write("<style> /* 显示多语种切换 */ .translateSelectLanguage{ display:block;background-color: rgba(255,255,255,.1);color: #ff9800 } </style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
