#server info
#test dev
server.id = 10001
server.openTime = 20190101000102
server.num = 1
server.sendlog37 = false
server.logDir = ../logs
server.arenaCross =true
server.deathPathCross =true
server.guildFight = false

server.autoOpen = true

server.debug = true

server.openAdultCheck = false
server.threadNum = 50
server.userDataLoaderEnabled = false

# redis config
spring.redis.database=0
#spring.redis.database=2
#spring.redis.host=60.1.1.21
#-----\u6D4B\u8BD5\u670D------
#spring.redis.host=120.92.119.145
#spring.redis.port=6080
#spring.redis.password=@emiplay_m5fangzhi_redis
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=
#-----\u672C\u5730------
#spring.redis.host=127.0.0.1
#spring.redis.port=6379
#spring.redis.password=

spring.redis.pool.max-active=8
spring.redis.pool.max-wait=-1
spring.redis.pool.max-idle=8
spring.redis.pool.min-idle=0
spring.redis.timeout=0

spring.redis.expireTi
me = -1

#spring.data.mongodb.uri = mongodb://mongouser:ysj#2017#ljsd@111.231.54.96:27017/ysj_wx_1
#spring.data.mongodb2.uri = mongodb://mongouser:ysj#2017#ljsd@111.231.54.96:27017/develop_ysj_wx_1
#mongodb2 develop

spring.data.mongodb.uri = mongodb://127.0.0.1:27017/m5_x1_game_10001
mongo.uriDbNamePrefix = m5_x1_game_
spring.data.mongodbcore.uri = mongodb://127.0.0.1:27017/m5_x1_login

#spring.data.mongodb.uri = mongodb://root:KJM!45kz6z#k8@120.92.216.50:27017/game_10001?authSource=admin
#mongo.uriDbNamePrefix = game_
#spring.data.mongodbcore.uri = mongodb://root:KJM!45kz6z#k8@120.92.216.50:27017/game_10001?authSource=admin

#spring.data.mongodbcore.uri = mongodb://admin:123456@120.92.119.145:27020/m5_n1_login?authSource=admin
#spring.data.mongodb.uri = mongodb://60.1.1.14:27017/jieling_10212
mongodb.options.maxWaitTime = 120000
mongodb.options.connectTimeout = 1000
mongodb.options.socketTimeout = 0
mongodb.options.threadsAllowedToBlockForConnectionMultiplier = 20
mongodb.options.connectionsPerHost = 256
mongodb.options.minConnectionsPerHost = 5
mongodb.options.maxConnectionIdleTime = 1000


# netty config
netty.tcpPort = 16081
netty.chatTcpPort = 20001
netty.logintcpPort = 17091
netty.udpPort = 17092
## netty.udpTargetIp \u00FB\uFFFD\uFFFD\uFFFD\uFFFD
#netty.udpTargetIp=60.1.1.212
netty.udpTargetPort=10001
netty.reconnectDelay=3000
netty.bossThreadCount=1
netty.workerThreadCount=10
netty.readTimeout=60
netty.writeTimeout=60
netty.allTimeout=60




#core     ##\uFFFD\uFFFDsdk\uFFFD\uFFFD\u02B1\uFFFD\uFFFD\uFFFD\uFFFD\u00F5\uFFFD

services.core.ip=127.0.0.1
services.core.port=7915
services.core.gmport=7916
services.core.worldport=7108
services.core.area=1000
services.core.id=1
services.core.weight=5


server.openCross = true
services.core.chatip=127.0.0.1
services.core.chatport=17181
services.core.gamechatport=7920

services.core.globalip=127.0.0.1
services.core.globalport=17080

xxl.job.enabled=true
xxl.job.admin.addresses=http://127.0.0.1:83/xxl-job-admin
xxl.job.accessToken=default_token
xxl.job.executor.appname=other${server.id}
xxl.job.executor.address=
xxl.job.executor.ip=
xxl.job.executor.port=9999
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
xxl.job.executor.logretentiondays=30

logging.config = classpath:logback-boot.xml