#server info
server.id = 20011
server.openTime = 20190101000102
server.num = 1
server.sendlog37 = false
server.logDir = ../logs

server.guildFight = false

server.autoOpen = true

server.debug = true

server.openAdultCheck = false

# redis config
spring.redis.database=0
#spring.redis.database=2
#spring.redis.host=60.1.1.21
spring.redis.host=10.0.0.24
spring.redis.port=6080
spring.redis.password=@emiplay_m5fangzhi_redis
spring.redis.pool.max-active=8
spring.redis.pool.max-wait=-1
spring.redis.pool.max-idle=8
spring.redis.pool.min-idle=0
spring.redis.timeout=0

spring.redis.expireTime = -1


#spring.data.mongodb.uri = mongodb://mongouser:ysj#2017#ljsd@111.231.54.96:27017/ysj_wx_1
#spring.data.mongodb2.uri = mongodb://mongouser:ysj#2017#ljsd@111.231.54.96:27017/develop_ysj_wx_1
#mongodb2 develop
spring.data.mongodb.uri = mongodb://admin:123456@10.0.0.24:27020/m5_tk_game_10011?authSource=admin
mongo.uriDbNamePrefix = m5_tk_game_
spring.data.mongodbcore.uri = mongodb://admin:123456@10.0.0.24:27020/m5_tk_login?authSource=admin
#spring.data.mongodb.uri = mongodb://60.1.1.14:27017/jieling_10212
mongodb.options.maxWaitTime = 120000
mongodb.options.connectTimeout = 1000
mongodb.options.socketTimeout = 0
mongodb.options.threadsAllowedToBlockForConnectionMultiplier = 20
mongodb.options.connectionsPerHost = 256
mongodb.options.minConnectionsPerHost = 5
mongodb.options.maxConnectionIdleTime = 1000


# netty config
netty.tcpPort = 16081
netty.chatTcpPort = 20001
netty.logintcpPort = 18091
netty.udpPort = 18092
## netty.udpTargetIp 没用上
#netty.udpTargetIp=60.1.1.212
netty.udpTargetPort=10001
netty.reconnectDelay=3000
netty.bossThreadCount=1
netty.workerThreadCount=10
netty.readTimeout=10
netty.writeTimeout=10
netty.allTimeout=10



#core     ##接sdk的时候会用到
services.core.ip=127.0.0.1
services.core.port=7903
services.core.gmport=7904
services.core.area=1000
services.core.id=1
services.core.weight=5


logging.config = ../conf/logback-boot.xml

