-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('GMCommandProto_pb')


GMCOMMAND = protobuf.Descriptor();
local GMCOMMAND_COMMAND_FIELD = protobuf.FieldDescriptor();

GMCOMMAND_COMMAND_FIELD.name = "command"
GMCOMMAND_COMMAND_FIELD.full_name = ".com.ljsd.jieling.protocols.GMCommand.command"
GMCOMMAND_COMMAND_FIELD.number = 1
GMCOMMAND_COMMAND_FIELD.index = 0
GMCOMMAND_COMMAND_FIELD.label = 1
GMCOMMAND_COMMAND_FIELD.has_default_value = false
GMCOMMAND_COMMAND_FIELD.default_value = ""
GMCOMMAND_COMMAND_FIELD.type = 9
GMCOMMAND_COMMAND_FIELD.cpp_type = 9

GMCOMMAND.name = "GMCommand"
GMCOMMAND.full_name = ".com.ljsd.jieling.protocols.GMCommand"
GMCOMMAND.nested_types = {}
GMCOMMAND.enum_types = {}
GMCOMMAND.fields = {GMCOMMAND_COMMAND_FIELD}
GMCOMMAND.is_extendable = false
GMCOMMAND.extensions = {}

GMCommand = protobuf.Message(GMCOMMAND)

