--- 防止随着副本类型的增加，不停在MapMissionView中增加代码
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hahaha.
--- DateTime: 2019/7/23 10:34
--- 精英副本的处理
CarbonMissionTypeView = {}
local this = CarbonMissionTypeView
local carbonType = 0

function this:InitComponent(gameObject)
    -- 绑定红点
    this.redPoint = Util.GetGameObject(gameObject, "rightUp/btnBack/redPoint")

end

function this:BindEvent()

end

-- 此方法会在普通跟精英副本执行
function this:InitShow(type)
    if type and type > 0 then
        carbonType = type
    end

    -- 初始化红点
    this.redPoint:SetActive(false)

    if carbonType == 3 then
        -- 精英副本显示初始化
        this:InitOpen()
    end
end

function this:InitOpen()

end

function this:OnBackBtnClick()
    if CarbonManager.difficulty == 3 then
        this.redPoint:SetActive(false)
    end
end

function this:RefreshMission(isMissionDone)
    if carbonType == 3 then
        this.redPoint:SetActive(isMissionDone)
    end
end

return CarbonMissionTypeView