PokemonEffectConfig = {
    [1] = {
        live = "live2d_s_jieling_dlg_3010",
        scale = 0.6,
        screen = "s_jieling_dlg_3010_skeff_casting_screeneff",
        screenCD = 3,
        hit1 = "s_jieling_dlg_3010_skeff_casting_buff",
        aoe = "s_jieling_dlg_3010_skeff_casting_attacked",
        icon = "s_jieling_dlg_3010_t1",
    },
    [2] = {
        live = "live2d_s_jieling_zlz_3001",
        scale = 0.7,
        screen = "s_jieling_zlz_3001_skeff_casting_screeneff",
        screenCD = 2.5,
        hit1 = "s_jieling_zlz_3001_skeff_casting_buff",
        aoe = "s_jieling_zlz_3001_skeff_casting_attacked",
        icon = "s_jieling_zlz_3001_t1",
    },
    [3] = {
        live = "live2d_s_jieling_hg_3002",
        scale = 0.7,
        screen = "s_jieling_hg_3002_skeff_casting_screeneff",
        screenCD = 3,
        hit1 = "s_jieling_hg_3002_skeff_casting_buff",
        aoe = "s_jieling_hg_3002_skeff_casting_attacked",
        icon = "s_jieling_hg_3002_t1",
    },
    [4] = {
        live = "live2d_s_jieling_jhj_3003",
        scale = 1,
        screen = "s_jieling_jhj_3003_skeff_casting_screeneff",
        screenCD = 3.5,
        hit1 = "s_jieling_jhj_3003_skeff_casting_buff",
        aoe = "s_jieling_jhj_3003_skeff_casting_attacked",
        icon = "s_jieling_jhj_3003_t1",
    },
    [5] = {
        live = "live2d_s_jieling_hs_3006",
        scale = 0.4,
        screen = "s_jieling_hs_3006_skeff_casting_screeneff",
        screenCD = 2,
        hit1 = "s_jieling_hs_3006_skeff_casting_buff_01",
        aoe = "s_jieling_hs_3006_skeff_casting_attacked",
        icon = "s_jieling_hs_3006_t1",
    },
    [6] = {
        live = "live2d_s_jieling_lms_3009",
        scale = 0.7,
        screen = "s_jieling_lms_3009_skeff_casting_screeneff",
        screenCD = 3,
        hit1 = "s_jieling_lms_3009_skeff_casting_buff01",
        aoe = "s_jieling_lms_3009_skeff_casting_attacked",
        icon = "s_jieling_lms_3009_t1",
    },
    [7] = {
        live = "live2d_s_jieling_sl_3005",
        scale = 0.8,
        screen = "s_jieling_sl_3005_skeff_casting_screeneff",
        screenCD = 3,
        hit1 = "s_jieling_sl_3005_skeff_casting_buff_01",
        aoe = "s_jieling_sl_3005_skeff_casting_attacked",
        icon = "s_jieling_sl_3005_t1",
    },
    [8] = {
        live = "live2d_s_jieling_md_3007",
        scale = 0.7,
        screen = "s_jieling_md_3007_skeff_casting_screeneff",
        screenCD = 3,
        hit1 = "s_jieling_md_3007_skeff_casting_buff_01",
        aoe = "s_jieling_md_3007_skeff_casting_attacked",
        icon = "s_jieling_md_3007_t1",
    },
    [9] = {
        live = "live2d_s_jieling_fl_3008",
        scale = 0.7,
        screen = "s_jieling_fl_3008_skeff_casting_screeneff",
        screenCD = 3,
        hit1 = "s_jieling_fl_3008_skeff_casting_buff_01",
        aoe = "s_jieling_fl_3008_skeff_casting_attacked",
        icon = "s_jieling_fl_3008_t1",
    },
    [10] = {
        live = "live2d_s_jieling_tl_3004",
        scale = 0.4,
        screen = "s_jieling_tl_3004_skeff_casting_screeneff",
        screenCD = 3,
        hit1 = "s_jieling_tl_3004_skeff_casting_buff01",
        aoe = "s_jieling_tl_3004_skeff_casting_attacked",
        icon = "s_jieling_tl_3004_t1",
    },
}