//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Colorful_HueSaturationValueWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Colorful.HueSaturationValue), typeof(Colorful.BaseEffect));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("MasterHue", get_MasterHue, set_MasterHue);
		L.RegVar("MasterSaturation", get_MasterSaturation, set_MasterSaturation);
		L.RegVar("MasterValue", get_MasterValue, set_MasterValue);
		L.RegVar("RedsHue", get_RedsHue, set_RedsHue);
		L.RegVar("RedsSaturation", get_RedsSaturation, set_RedsSaturation);
		L.RegVar("RedsValue", get_RedsValue, set_RedsValue);
		L.RegVar("YellowsHue", get_YellowsHue, set_YellowsHue);
		L.RegVar("YellowsSaturation", get_YellowsSaturation, set_YellowsSaturation);
		L.RegVar("YellowsValue", get_YellowsValue, set_YellowsValue);
		L.RegVar("GreensHue", get_GreensHue, set_GreensHue);
		L.RegVar("GreensSaturation", get_GreensSaturation, set_GreensSaturation);
		L.RegVar("GreensValue", get_GreensValue, set_GreensValue);
		L.RegVar("CyansHue", get_CyansHue, set_CyansHue);
		L.RegVar("CyansSaturation", get_CyansSaturation, set_CyansSaturation);
		L.RegVar("CyansValue", get_CyansValue, set_CyansValue);
		L.RegVar("BluesHue", get_BluesHue, set_BluesHue);
		L.RegVar("BluesSaturation", get_BluesSaturation, set_BluesSaturation);
		L.RegVar("BluesValue", get_BluesValue, set_BluesValue);
		L.RegVar("MagentasHue", get_MagentasHue, set_MagentasHue);
		L.RegVar("MagentasSaturation", get_MagentasSaturation, set_MagentasSaturation);
		L.RegVar("MagentasValue", get_MagentasValue, set_MagentasValue);
		L.RegVar("AdvancedMode", get_AdvancedMode, set_AdvancedMode);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MasterHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.MasterHue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MasterHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MasterSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.MasterSaturation;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MasterSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MasterValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.MasterValue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MasterValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RedsHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.RedsHue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RedsHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RedsSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.RedsSaturation;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RedsSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RedsValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.RedsValue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RedsValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_YellowsHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.YellowsHue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index YellowsHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_YellowsSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.YellowsSaturation;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index YellowsSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_YellowsValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.YellowsValue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index YellowsValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GreensHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.GreensHue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GreensHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GreensSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.GreensSaturation;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GreensSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GreensValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.GreensValue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GreensValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CyansHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.CyansHue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CyansHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CyansSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.CyansSaturation;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CyansSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CyansValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.CyansValue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CyansValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BluesHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.BluesHue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BluesHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BluesSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.BluesSaturation;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BluesSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BluesValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.BluesValue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BluesValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MagentasHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.MagentasHue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MagentasHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MagentasSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.MagentasSaturation;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MagentasSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MagentasValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float ret = obj.MagentasValue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MagentasValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AdvancedMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			bool ret = obj.AdvancedMode;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AdvancedMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MasterHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.MasterHue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MasterHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MasterSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.MasterSaturation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MasterSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MasterValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.MasterValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MasterValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RedsHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.RedsHue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RedsHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RedsSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.RedsSaturation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RedsSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_RedsValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.RedsValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index RedsValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_YellowsHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.YellowsHue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index YellowsHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_YellowsSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.YellowsSaturation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index YellowsSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_YellowsValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.YellowsValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index YellowsValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GreensHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.GreensHue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GreensHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GreensSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.GreensSaturation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GreensSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_GreensValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.GreensValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index GreensValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CyansHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.CyansHue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CyansHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CyansSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.CyansSaturation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CyansSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CyansValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.CyansValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CyansValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BluesHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.BluesHue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BluesHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BluesSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.BluesSaturation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BluesSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_BluesValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.BluesValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index BluesValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MagentasHue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.MagentasHue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MagentasHue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MagentasSaturation(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.MagentasSaturation = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MagentasSaturation on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_MagentasValue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.MagentasValue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MagentasValue on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AdvancedMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Colorful.HueSaturationValue obj = (Colorful.HueSaturationValue)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.AdvancedMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index AdvancedMode on a nil value");
		}
	}
}

