//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameCore_Singleton_GameLogic_UpdateManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameCore.Singleton<GameLogic.UpdateManager>), typeof(System.Object), "Singleton_GameLogic_UpdateManager");
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, GameCore.Singleton<GameLogic.UpdateManager>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

