//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ImageHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ImageHelper), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("StopCo", StopCo);
		L.RegFunction("ResetFillImage", ResetFillImage);
		L.RegFunction("FillImage", FillImage);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopCo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ImageHelper obj = (ImageHelper)ToLua.CheckObject<ImageHelper>(L, 1);
			obj.StopCo();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetFillImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ImageHelper obj = (ImageHelper)ToLua.CheckObject<ImageHelper>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.ResetFillImage(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FillImage(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			ImageHelper obj = (ImageHelper)ToLua.CheckObject<ImageHelper>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
			obj.FillImage(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

