//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NotchScreenUtilWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NotchScreenUtil), typeof(System.Object));
		L.RegFunction("Init", Init);
		L.RegFunction("GetNotchHeight", GetNotchHeight);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NotchScreenUtil obj = (NotchScreenUtil)ToLua.CheckObject<NotchScreenUtil>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNotchHeight(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NotchScreenUtil obj = (NotchScreenUtil)ToLua.CheckObject<NotchScreenUtil>(L, 1);
			int o = obj.GetNotchHeight();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, NotchScreenUtil.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

