//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ResUpdate_ResourcesUpdateStateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(ResUpdate.ResourcesUpdateState));
		L.RegVar("GetGameConfigs", get_GetGameConfigs, null);
		L.RegVar("GetGameConfigsFailed", get_GetGameConfigsFailed, null);
		L.RegVar("DownLoadVersionFiles", get_DownLoadVersionFiles, null);
		L.RegVar("DownLoadVersionFilesFailed", get_DownLoadVersionFilesFailed, null);
		L.RegVar("DownLoadFromNoWifi", get_DownLoadFromNoWifi, null);
		L.RegVar("DownLoadWithWifi", get_DownLoadWithWifi, null);
		L.RegVar("UpdateResourcesProgress", get_UpdateResourcesProgress, null);
		L.RegVar("UpdateResourcesFailed", get_UpdateResourcesFailed, null);
		L.RegVar("Success", get_Success, null);
		L.RegVar("OldPackageNeedChange", get_OldPackageNeedChange, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<ResUpdate.ResourcesUpdateState>.Check = CheckType;
		StackTraits<ResUpdate.ResourcesUpdateState>.Push = Push;
	}

	static void Push(IntPtr L, ResUpdate.ResourcesUpdateState arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(ResUpdate.ResourcesUpdateState), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetGameConfigs(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.GetGameConfigs);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetGameConfigsFailed(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.GetGameConfigsFailed);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DownLoadVersionFiles(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.DownLoadVersionFiles);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DownLoadVersionFilesFailed(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.DownLoadVersionFilesFailed);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DownLoadFromNoWifi(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.DownLoadFromNoWifi);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DownLoadWithWifi(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.DownLoadWithWifi);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UpdateResourcesProgress(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.UpdateResourcesProgress);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UpdateResourcesFailed(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.UpdateResourcesFailed);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Success(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.Success);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OldPackageNeedChange(IntPtr L)
	{
		ToLua.Push(L, ResUpdate.ResourcesUpdateState.OldPackageNeedChange);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		ResUpdate.ResourcesUpdateState o = (ResUpdate.ResourcesUpdateState)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

