
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=
spring.redis.pool.max-active=8
spring.redis.pool.max-wait=-1
spring.redis.pool.max-idle=8
spring.redis.pool.min-idle=0

#core
services.core.ip=127.0.0.1
services.core.port=17181
services.core.area=1000
services.core.id=1
services.core.weight=5

logging.config = C:/Users/yuan/Desktop/bin-srv-jar-deploy/bin-srv-jar/assets/conf/logback-boot.xml