---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by aaa.
--- DateTime: 2019/8/30 15:43
---
local RewardView = quick_class("RewardView")
local _BloodyRankConfig = ConfigManager.GetConfig(ConfigName.BloodyRankConfig)
local _ItemList = {}    -- 物品管理

function RewardView:ctor(parent, root)
    self.root = root
    self:InitComponent(root)
    self:BindEvent()

end

function RewardView:InitComponent(root)
    self.itemRoot = Util.GetGameObject(root, "treasureList/viewPort/content")
    self.item = Util.GetGameObject(self.itemRoot, "itemPro")
    self.myPos = Util.GetGameObject(root, "info/pos"):GetComponent("Text")

    -- 刷新列表显示
    self:RefreshRankList()
end

function RewardView:BindEvent(root)
end


function RewardView:OnShow()
    self.root:SetActive(true)

    self.myPos.text = MatchDataManager.GetNickNameByScore(MatchDataManager.GetMyScore())
end

-- 刷新列表显示
function RewardView:RefreshRankList()
    local _ItemIndex = 0
    for _, data in ConfigPairs(_BloodyRankConfig) do
        local node = newObjToParent(self.item, self.itemRoot)
        local posName = Util.GetGameObject(node, "name"):GetComponent("Text")
        local itemBox = Util.GetGameObject(node, "itembox").transform
        -- 段位
        posName.text = data.Name
        -- 创建奖励物品
        for i = 1, #data.Reward do
            local reward = data.Reward[i]
            _ItemIndex = _ItemIndex + 1
            local item = _ItemList[_ItemIndex]
            if not item then
                item = SubUIManager.Open(SubUIConfig.ItemView, itemBox)
                _ItemList[_ItemIndex] = item
            end
            item:OnOpen(false, reward, 0.75)
            item.transform:SetParent(itemBox)
        end

    end
end

function RewardView:ReShowPanel()

end

function RewardView:OnHidePanel()
    self.root:SetActive(false)
end

-- 回收物品
function RewardView:OnDestroy()
    for _, item in pairs(_ItemList) do
        SubUIManager.Close(item)
    end
    _ItemList = {}
end

return RewardView