#spring.config.name=application
#spring.config.location=classpath:/,file:./config/

# +++++++++++ logging config ++++++++++
logging.config = ./assets/conf/logback-boot.xml


# +++++++++++ redis config ++++++++++
spring.redis.database=2
# -- for docker
#spring.redis.host=host.docker.internal
spring.redis.host=127.0.0.1
spring.redis.port=9500
spring.redis.password=foo9500
spring.redis.pool.max-active=8
spring.redis.pool.max-wait=-1
spring.redis.pool.max-idle=8
spring.redis.pool.min-idle=0


# +++++++++++ mongodb config ++++++++++
#mongodb.port=27027 default
#spring.data.mongodb.uri = mongodb://host.docker.internal:27037/game_10001?authSource=admin
#spring.data.mongodbcore.uri = mongodb://host.docker.internal:27037/game_10001?authSource=admin
spring.data.mongodb.uri = mongodb://127.0.0.1:27037/game_10001?authSource=admin
spring.data.mongodbcore.uri = mongodb://127.0.0.1:27037/game_10001?authSource=admin
mongo.uriDbNamePrefix = game_
# -- use user and pwd
#spring.data.mongodb.uri = mongodb://root:KJM!45kz6z#k8@120.92.216.50:27017/game_10001?authSource=admin
#spring.data.mongodbcore.uri = mongodb://root:KJM!45kz6z#k8@120.92.216.50:27017/game_10001?authSource=admin
#mongo.uriDbNamePrefix = game_

mongodb.options.maxWaitTime = 120000
mongodb.options.connectTimeout = 1000
mongodb.options.socketTimeout = 0
mongodb.options.threadsAllowedToBlockForConnectionMultiplier = 20
mongodb.options.connectionsPerHost = 256
mongodb.options.minConnectionsPerHost = 5
mongodb.options.maxConnectionIdleTime = 1000


# +++++++++++ own config ++++++++++
services.core.ip=127.0.0.1
services.core.port=11300
services.core.area=1000
services.core.id=1
services.core.weight=5
