# +++++++++++ server info config ++++++++++
server.id = 10001
server.openTime = 20190101000102
server.num = 1
server.sendlog37 = false
server.logDir = ./assets/log
server.arenaCross =true
server.deathPathCross =true
server.guildFight = false

server.autoOpen = true
server.debug = true

server.openAdultCheck = false
server.threadNum = 50
server.userDataLoaderEnabled = false

# +++++++++++ logging config ++++++++++
logging.config = ./assets/conf/logback-boot.xml

# +++++++++++ redis config ++++++++++
spring.redis.database=0
#spring.redis.host=host.docker.internal
spring.redis.host=127.0.0.1
#spring.redis.port=6379   default port
spring.redis.port=9500
spring.redis.password=foo9500

spring.redis.pool.max-active=8
spring.redis.pool.max-wait=-1
spring.redis.pool.max-idle=8
spring.redis.pool.min-idle=0
spring.redis.timeout=0
spring.redis.expireTime= -1


# +++++++++++ mongodb config ++++++++++
#mongodb.port=27027 default
#spring.data.mongodb.uri = mongodb://host.docker.internal:27037/game_10001?authSource=admin
#spring.data.mongodbcore.uri = mongodb://host.docker.internal:27037/game_10001?authSource=admin
spring.data.mongodb.uri = mongodb://127.0.0.1:27037/game_10001?authSource=admin
spring.data.mongodbcore.uri = mongodb://127.0.0.1:27037/game_10001?authSource=admin
mongo.uriDbNamePrefix = game_
# -- use user and pwd
#spring.data.mongodb.uri = mongodb://root:KJM!45kz6z#k8@120.92.216.50:27017/game_10001?authSource=admin
#spring.data.mongodbcore.uri = mongodb://root:KJM!45kz6z#k8@120.92.216.50:27017/game_10001?authSource=admin
#mongo.uriDbNamePrefix = game_

mongodb.options.maxWaitTime = 120000
mongodb.options.connectTimeout = 1000
mongodb.options.socketTimeout = 0
mongodb.options.threadsAllowedToBlockForConnectionMultiplier = 20
mongodb.options.connectionsPerHost = 256
mongodb.options.minConnectionsPerHost = 5
mongodb.options.maxConnectionIdleTime = 1000


# +++++++++++ netty config ++++++++++
netty.tcpPort = 11400
netty.chatTcpPort = 20001
netty.logintcpPort = 17901
netty.udpPort = 17092
## netty.udpTargetIp \u00FB\uFFFD\uFFFD\uFFFD\uFFFD
#netty.udpTargetIp=60.1.1.212
netty.udpTargetPort=10001
netty.reconnectDelay=3000
netty.bossThreadCount=1
netty.workerThreadCount=10
netty.readTimeout=60
netty.writeTimeout=60
netty.allTimeout=60

# +++++++++++ own config ++++++++++
services.core.ip=127.0.0.1
services.core.port=7915
services.core.gmport=7916
services.core.worldport=7108
services.core.area=1000
services.core.id=1
services.core.weight=5

server.openCross = true
services.core.chatip=127.0.0.1
services.core.chatport=11300
services.core.gamechatport=7920
services.core.globalip=127.0.0.1
services.core.globalport=17080

# +++++++++++ job config ++++++++++
xxl.job.enabled=false
xxl.job.admin.addresses=http://120.92.216.50:83/xxl-job-admin
xxl.job.accessToken=default_token
xxl.job.executor.appname=other${server.id}
xxl.job.executor.address=
xxl.job.executor.ip=
xxl.job.executor.port=9999
xxl.job.executor.logpath=./assets/log/xxl-job/jobhandler
xxl.job.executor.logretentiondays=30
